var currentDT = new Date();
console.log(currentDT);
var currentTimeUnix = currentDT.getTime();
console.log(currentTimeUnix);
var currfy = currentDT.getFullYear();
var currgd = currentDT.getDay();
var currgm = currentDT.getMonth();
var currds = currentDT.toDateString();
console.log(currfy);
console.log(currgd);
console.log(currgm);
console.log(currds);
var currgmi = currentDT.getMilliseconds();
var currgto = currentDT.getTimezoneOffset();
console.log(currgmi);
console.log(currgto);
var currut = currentDT.getUTCDate();
var currlo  = currentDT.toLocaleString();
console.log(currut);
console.log(currlo);
var someDateTime = 1773311623872;
var cdt = new Date(1773311623872);
console.log(cdt.getDate());
var someRandom = "12/12/2020";
var cr = new Date(someRandom).getTime();
console.log(cr);
